language: php
php:
    - 5.5
    - 5.6
    - hhvm
env:
    global:
        - CORE_BRANCH=stable8.1
    matrix:
        - DB=pgsql

matrix:
    allow_failures:
        - php: hhvm
        - php: 7
        - env: DB=pgsql CORE_BRANCH=master 
    include:
        - php: 5.5
          env: DB=sqlite
        - php: 5.5
          env: DB=mysql
        - php: 5.5
          env: DB=pgsql CORE_BRANCH=master
        # experimental PHP 7 features
        - php: 7
          env: DB=pgsql CORE_BRANCH=master
        # master branch
        - php: 5.5
          env: DB=pgsql CORE_BRANCH=master
    fast_finish: true
